### ISSUE TITLE
Procedural code with OOP

### ISSUE THREAD

**Issue by szepeviktor** [ItalyStrap/html#5]
Project usually place helpers.php in the same dir. as OOP code.
See Symfony and Laravel.

**Comment by szepeviktor** [comment]
While you're at it you may nuke the useless `HTML` directory :)

`"ItalyStrap\\HTML\\": "src/"`

**Comment by overclokk** [comment]
I was thinking about that, what is the better place to put helpers? There's no a standard, some put in src and some in dedicated directory outside src, I don't know yet what is my preferred style for that :-D

> 
> 
> While you're at it you may nuke the useless `HTML` directory :)
> 
> `"ItalyStrap\\HTML\\": "src/"`

Yes, I know, it was a copy and paste from the theme :-D

**Comment by szepeviktor** [comment]
Helpers are in the same namespace so they could live in /src - although they are not psr-4 loaded.

**Comment by overclokk** [comment]
Ok, you convinced me.
