### ISSUE TITLE
Order of tests

### ISSUE THREAD

**Issue by szepeviktor** [ItalyStrap/html#6]
```
  - codecept run unit
#  - codecept run wpunit && codecept run unit
  - phpstan analyse
  - phpcs -p --standard=PHPCompatibility src
  - phpcs -p --standard=PSR1 src
```

It is highly advised to run dumber tests first and use composer scripts.

```
  - composer check
  - codecept run unit
```

**Comment by szepeviktor** [comment]
I talk developer teams into using

- syntax check
- coding standard
- static analysis

these are zero-coverage tests, thus no code is necessary.

**Comment by overclokk** [comment]
Just added my custom rules, for now WPCS is skipped.
