### ISSUE TITLE
Base values in PHP

### ISSUE THREAD

**Issue by szepeviktor** [ItalyStrap/html#7]
AFAIK base value in PHP is null.
But for arrays one should use `[]`, for strings `''`.

I've spot null/array mix in the code. Please consider using the above.

`public function render( string $context, $args = null ): string {`

**Comment by szepeviktor** [comment]
WordPress has a lot of abnormal things: one of them is using false as base value, or returning WP_Error instead throwing an exception.

**Comment by overclokk** [comment]
The `$args` argument was intended for passing any type of data to the hook (primitive, object), I know that `null` is wrong but `mixed` does not exists.

**Comment by szepeviktor** [comment]
I see!
`null` is the best default value for unknown types.
