### ISSUE TITLE
Boolean as an argument

### ISSUE THREAD

**Issue by szepeviktor** [ItalyStrap/html#8]
You may read unlimited number :) of articles on the web why a bool should not be an argument.

```php
function mixit(bool $echo) {}

// should be instead

function getit(): string {}
// and
function printit(): void
{
    print getit();
}
```

**Comment by overclokk** [comment]
This https://github.com/ItalyStrap/html/blob/aef19ab6e794592896207f479bd3c005cb9c5b0b/src/helpers.php#L21 was a legacy code, if I change that I will break a lot of thing, I added `get_attr_e()` to echo the string, maybe I could add a `_deprecated_argument()` to that function to tel dev to change function call.

**Comment by szepeviktor** [comment]
I see.
I thought ItalyStrap/html is brand new project.

**Comment by overclokk** [comment]
All repos in this Organization are module for the ItalyStrap theme and ACM plugin, because I need them in other project I separate each module in its own repo for require them with composer.
